name: Deploy to Azure Container App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f src/dockerfile -t ${{ secrets.DOCKER_USERNAME }}/merchstore:latest ./src
          docker push ${{ secrets.DOCKER_USERNAME }}/merchstore:latest

      - name: Install Azure CLI (Ensure Latest Version)
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update container image and set environment variables
        run: |
          az containerapp update \
            --name northwaddleapp \
            --resource-group NorthWaddleRG \
            --image ${{ secrets.DOCKER_USERNAME }}/merchstore:latest \
            --set-env-vars \
              CONNECTION_STRING="${{ secrets.AZURE_SQL_DB_CONNECTIONSTRING }}" \
              API_KEY="${{ secrets.BASIC_PRODUCT_API_KEY }}" \
              ADMIN_USERNAME="${{ secrets.ADMIN_USER_USERNAME }}" \
              ADMIN_PASSWORD="${{ secrets.ADMIN_USER_PASSWORD }}" \
              ADMIN_EMAIL="${{ secrets.ADMIN_USER_EMAIL }}" \
              ADMIN_ROLE="${{ secrets.ADMIN_USER_ROLE }}" \
              APPLICATIONINSIGHTS_CONNECTIONSTRING="${{ secrets.APPLICATIONINSIGHTS_CONNECTIONSTRING }}"
              AI_API_USERNAME="${{ secrets.AI_API_USERNAME }}" \
              AI_API_PASSWORD="${{ secrets.AI_API_PASSWORD }}"
